# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# load antigen
source $HOME/.antigen.zsh

# load plugins
antigen use oh-my-zsh
antigen bundle z
antigen bundle git
antigen bundle docker
antigen bundle vscode
antigen bundle mattberther/zsh-pyenv
antigen bundle greymd/docker-zsh-completion
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

# load theme
antigen theme romkatv/powerlevel10k

# apply
antigen apply

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# other imports
[[ ! -f ~/.aliases ]] || source ~/.aliases

