#!/bin/bash
pidfile=/tmp/yabai-helper-pid
read -r w_id w_fl <<< $(yabai -m query --windows --window | jq -r '.id, ."is-floating"')

## Configuration

# Grid Move for Floating Windows (arg to --grid)
# <rows>:<cols>:<start-x>:<start-y>:<width>:<height>
GRID_WEST="3:3:0:0:2:3"
GRID_EAST="3:3:2:0:1:3"
GRID_NORTH="3:3:2:0:1:1"
GRID_SOUTH="3:3:2:1:1:2"

## Functions

hlActiveWindow() {
  # get active color without transparency
  color=$(yabai -m config active_window_border_color)
  color=${color: 2}
  color=$(printf %6s "${color: -6}" | tr ' ' 0)

  # animate
  for i in $(seq 255 -12 0)
  do
    s=$(printf '%x' $i);
    yabai -m config active_window_border_color 0x${s}${color}
  done
}

## Initialization

# if another instance exists, kill it
if [[ -f "$pidfile" ]]; then
  kill -9 $(<"$pidfile")
fi

# store our pid so we can be killed
echo $$ > $pidfile

## Parse Arguments

case $1 in 
  focus-window)
    case $2 in
      north)
        yabai -m window --focus north || yabai -m display --focus north 
        ;;
      south)
        yabai -m window --focus south || yabai -m display --focus south
        ;;
      west)
        yabai -m window --focus west || yabai -m space --focus prev
        ;;
      east)
        yabai -m window --focus east || yabai -m space --focus next
        ;;
      stack.prev)
        yabai -m window --focus stack.prev || yabai -m window --focus stack.last
        ;;
      stack.next)
        yabai -m window --focus stack.next || yabai -m window --focus stack.first
        ;;
      *)
        echo -n "Invalid argument for focus-window."
    esac
    hlActiveWindow
    ;;

  move-window)
    if [[ $w_fl == "false" ]]; then
      case $2 in 
        west)
          yabai -m window --swap $2 || yabai -m window --space prev || yabai -m window --display $2
          ;;
        east)
          yabai -m window --swap $2 || yabai -m window --space next || yabai -m window --display $2
          ;;
        *)
          yabai -m window --swap $2 || yabai -m window --display $2
      esac
      yabai -m window --focus $w_id
      hlActiveWindow
    else
      case $2 in
        north) yabai -m window --grid $GRID_NORTH ;;
        south) yabai -m window --grid $GRID_SOUTH ;;
        east) yabai -m window --grid $GRID_EAST ;;
        west) yabai -m window --grid $GRID_WEST ;;
      esac
    fi
    ;;

  toggle-layout)
    if [[ $(yabai -m config layout) = "bsp" ]]; then
      yabai -m config layout float
    else
      yabai -m config layout bsp
    fi
    ;;

  stack-window)
    # stack onto existing stack if possible
    yabai -m window $2 --stack $w_id
    if [[ $? -ne 0 ]]; then
      yabai -m window --insert $2
      yabai -m window $window --toggle float
      yabai -m window $window --toggle float
    fi
    ;;

  *)
    echo -n "Invalid command."
    ;;

esac

# delete pid file
rm -f $pidfile
